import tokyoNight from "shiki/themes/tokyo-night.mjs";
import type { ThemeRegistrationRaw } from "shiki";

const stormForeground: Record<string, string> = {
  "#51597d": "#5f6996",
  "#5a638c": "#6f7bb0",
  "#646e9c": "#7582ba",
  "#0db9d7": "#2ac3de",
};

const settings = (tokyoNight.tokenColors ?? []).map((setting) => {
  const foreground = setting.settings?.foreground;
  return {
    ...setting,
    settings: {
      ...setting.settings,
      ...(foreground
        ? {
            foreground: stormForeground[foreground.toLowerCase()] ?? foreground,
          }
        : {}),
    },
  };
});

export default {
  ...tokyoNight,
  name: "tokyo-night-storm",
  displayName: "Tokyo Night Storm",
  colors: {
    ...tokyoNight.colors,
    foreground: "#8089b3",
    descriptionForeground: "#545c7e",
    errorForeground: "#5a607d",
    "badge.background": "#7e83b233",
    "badge.foreground": "#a9b1d6",
    "icon.foreground": "#8089b3",
    "toolbar.activeBackground": "#2c324a",
    "toolbar.hoverBackground": "#2c324a",
    "button.secondaryBackground": "#41496b",
    "input.background": "#1b1e2e",
    "input.border": "#282e44",
    "input.placeholderForeground": "#4a5272",
    "dropdown.foreground": "#8089b3",
    "dropdown.background": "#1b1e2e",
    "dropdown.listBackground": "#1b1e2e",
    "activityBar.background": "#1f2335",
    "activityBar.foreground": "#8089b3",
    "activityBar.inactiveForeground": "#41496b",
    "activityBar.border": "#1f2335",
    "activityBarTop.foreground": "#8089b3",
    "activityBarTop.inactiveForeground": "#41496b",
    "tree.indentGuidesStroke": "#2e344f",
    "sideBar.foreground": "#8089b3",
    "sideBar.background": "#1f2335",
    "sideBar.border": "#1b1e2e",
    "sideBarTitle.foreground": "#8089b3",
    "sideBarSectionHeader.background": "#1f2335",
    "sideBarSectionHeader.border": "#1b1e2e",
    "sideBar.dropBackground": "#292e42",
    "list.dropBackground": "#292e42",
    "list.deemphasizedForeground": "#8089b3",
    "list.activeSelectionBackground": "#2c324a",
    "list.inactiveSelectionBackground": "#292e42",
    "list.focusBackground": "#292e42",
    "list.hoverBackground": "#1b1e2e",
    "listFilterWidget.background": "#1b1e2e",
    "pickerGroup.border": "#1b1e2e",
    "scrollbarSlider.background": "#9cacff15",
    "scrollbarSlider.hoverBackground": "#9cacff10",
    "scrollbarSlider.activeBackground": "#9cacff22",
    "editorBracketHighlight.foreground6": "#cfa25f",
    "editorBracketPairGuide.activeBackground6": "#cfa25f",
    "selection.background": "#6f7bb635",
    "editor.background": "#24283b",
    "editor.foldBackground": "#181b294a",
    "editorLink.activeForeground": "#a9b1d6",
    "editor.selectionBackground": "#6f7bb640",
    "editor.inactiveSelectionBackground": "#6f7bb615",
    "editor.findMatchBorder": "#ffdb69aa",
    "editor.findRangeHighlightBackground": "#6f7bb625",
    "editor.rangeHighlightBackground": "#6f7bb620",
    "editor.wordHighlightBackground": "#6f7bb633",
    "editor.wordHighlightStrongBackground": "#6f7bb644",
    "editor.selectionHighlightBackground": "#6f7bb633",
    "editorIndentGuide.background1": "#2d324a",
    "editorIndentGuide.activeBackground1": "#3b4261",
    "editorLineNumber.foreground": "#3b4261",
    "editorLineNumber.activeForeground": "#8089b3",
    "editor.lineHighlightBackground": "#292e42",
    "editorWhitespace.foreground": "#3b4261",
    "editorMarkerNavigation.background": "#1f2335",
    "editorHoverWidget.background": "#1f2335",
    "editorHoverWidget.border": "#1b1e2e",
    "editorBracketMatch.background": "#1f2335",
    "editorBracketMatch.border": "#545c7e",
    "editorOverviewRuler.border": "#1b1e2e",
    "editorOverviewRuler.bracketMatchForeground": "#1b1e2e",
    "editorOverviewRuler.modifiedForeground": "#3d547a",
    "editorRuler.foreground": "#1b1e2e",
    "editorGutter.modifiedBackground": "#3d547a",
    "editorGhostText.foreground": "#7582ba",
    "minimapGutter.modifiedBackground": "#3d547a",
    "editorGroup.border": "#1b1e2e",
    "editorGroup.emptyBackground": "#24283b",
    "editorGroup.dropBackground": "#292e42",
    "editorGroupHeader.tabsBorder": "#1b1e2e",
    "editorGroupHeader.tabsBackground": "#1f2335",
    "editorGroupHeader.noTabsBackground": "#1f2335",
    "editorGroupHeader.border": "#1b1e2e",
    "editorPane.background": "#24283b",
    "editorWidget.foreground": "#8089b3",
    "editorWidget.background": "#1f2335",
    "editorWidget.border": "#1b1e2e",
    "editorSuggestWidget.background": "#1f2335",
    "editorSuggestWidget.border": "#1b1e2e",
    "editorSuggestWidget.selectedBackground": "#282e44",
    "editorSuggestWidget.highlightForeground": "#668ac4",
    "editorCodeLens.foreground": "#5f6996",
    "editorInlayHint.foreground": "#7582ba",
    "peekView.border": "#1b1e2e",
    "peekViewEditor.background": "#1f2335",
    "peekViewTitle.background": "#1b1e2e",
    "peekViewTitleDescription.foreground": "#8089b3",
    "peekViewResult.background": "#1b1e2e",
    "peekViewResult.fileForeground": "#8089b3",
    "diffEditor.diagonalFill": "#2c324a",
    "diffEditor.unchangedCodeBackground": "#2f344d66",
    "multiDiffEditor.headerBackground": "#24283b",
    "multiDiffEditor.border": "#24283b",
    "breadcrumb.background": "#1E2233",
    "breadcrumbPicker.background": "#1f2335",
    "breadcrumb.foreground": "#545c7e",
    "tab.activeBackground": "#1f2335",
    "tab.inactiveBackground": "#1f2335",
    "tab.inactiveForeground": "#8089b3",
    "tab.border": "#1b1e2e",
    "tab.unfocusedInactiveForeground": "#8089b3",
    "tab.activeModifiedBorder": "#282d42",
    "tab.inactiveModifiedBorder": "#282d42",
    "tab.unfocusedActiveBorder": "#3b4261",
    "tab.lastPinnedBorder": "#2c3147",
    "panel.background": "#1f2335",
    "panel.border": "#1b1e2e",
    "panelTitle.activeForeground": "#a9b1d6",
    "panelTitle.inactiveForeground": "#8089b3",
    "panelTitle.activeBorder": "#3d59a1",
    "panelInput.border": "#1f2335",
    "statusBar.foreground": "#8089b3",
    "statusBar.background": "#1f2335",
    "statusBar.border": "#1b1e2e",
    "statusBar.noFolderBackground": "#1f2335",
    "statusBar.debuggingBackground": "#1f2335",
    "statusBar.debuggingForeground": "#8089b3",
    "statusBarItem.activeBackground": "#1b1e2e",
    "statusBarItem.hoverBackground": "#282e44",
    "statusBarItem.prominentBackground": "#1b1e2e",
    "statusBarItem.prominentHoverBackground": "#282e44",
    "titleBar.activeForeground": "#8089b3",
    "titleBar.inactiveForeground": "#8089b3",
    "titleBar.activeBackground": "#1f2335",
    "titleBar.inactiveBackground": "#1f2335",
    "titleBar.border": "#1b1e2e",
    "walkThrough.embeddedEditorBackground": "#1f2335",
    "textLink.foreground": "#668ac4",
    "textPreformat.foreground": "#73daca",
    "textBlockQuote.background": "#1f2335",
    "textCodeBlock.background": "#1f2335",
    "textSeparator.foreground": "#545c7e",
    "debugExceptionWidget.background": "#1b1e2e",
    "debugToolBar.background": "#1b1e2e",
    "debugConsole.infoForeground": "#8089b3",
    "debugConsole.sourceForeground": "#8089b3",
    "editor.stackFrameHighlightBackground": "#e2bd3a20",
    "debugView.stateLabelForeground": "#8089b3",
    "debugView.stateLabelBackground": "#1b1e2e",
    "debugView.valueChangedHighlight": "#3d59a1cc",
    "debugIcon.breakpointDisabledForeground": "#545c7e",
    "terminal.background": "#1f2335",
    "terminal.foreground": "#8089b3",
    "terminal.selectionBackground": "#6f7bb640",
    "terminal.ansiBlack": "#414868",
    "terminal.ansiWhite": "#8089b3",
    "terminal.ansiBrightBlack": "#414868",
    "terminal.ansiBrightWhite": "#a9b1d6",
    "gitDecoration.ignoredResourceForeground": "#545c7e",
    "notebook.editorBackground": "#24283b",
    "notebook.cellEditorBackground": "#1f2335",
    "notebook.cellBorderColor": "#1b1e2e",
    "notebook.cellStatusBarItemHoverBackground": "#2c324a",
    "charts.green": "#73daca",
    "charts.lines": "#1f2335",
    "mergeEditor.conflict.unhandledFocused.border": "#e0af68d9",
    "gitlens.trailingLineForegroundColor": "#7582ba",
    "gitlens.gutterForegroundColor": "#8089b3",
    "gitlens.gutterBackgroundColor": "#1f2335",
    "notificationCenterHeader.background": "#1b1e2e",
    "notifications.background": "#1b1e2e",
    "menubar.selectionForeground": "#c0caf5",
    "menubar.selectionBackground": "#2f3549",
    "menu.foreground": "#8089b3",
    "menu.background": "#1f2335",
    "menu.selectionForeground": "#c0caf5",
    "menu.selectionBackground": "#2f3549",
    "menu.separatorBackground": "#1b1e2e",
    "menu.border": "#1b1e2e",
    "chat.requestBorder": "#282e44",
    "chat.slashCommandBackground": "#1b1e2e",
    "inlineChat.background": "#1b1e2e",
  },
  settings,
  tokenColors: settings,
} satisfies ThemeRegistrationRaw;
